// Generated by gencpp from file cav_msgs/Control.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_CONTROL_H
#define CAV_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cav_msgs
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : timestamp(0.0)
    , count(0)
    , brake_cmd(0.0)
    , throttle_cmd(0.0)
    , steering_cmd_front_wheel(0.0)
    , gear_cmd(0)
    , turn_signal_cmd(0)
    , speed_cmd(0.0)
    , acceleration_cmd(0.0)
    , bywire_control_enable(0)
    , emerg_brake(0)
    , front_light(0)
    , engine_enable(0)
    , park_enable(0)
    , vehicle_mode(0)
    , yaw_speed_cmd(0.0)
    , ey_out(0.0)
    , ephi_out(0.0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , count(0)
    , brake_cmd(0.0)
    , throttle_cmd(0.0)
    , steering_cmd_front_wheel(0.0)
    , gear_cmd(0)
    , turn_signal_cmd(0)
    , speed_cmd(0.0)
    , acceleration_cmd(0.0)
    , bywire_control_enable(0)
    , emerg_brake(0)
    , front_light(0)
    , engine_enable(0)
    , park_enable(0)
    , vehicle_mode(0)
    , yaw_speed_cmd(0.0)
    , ey_out(0.0)
    , ephi_out(0.0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _count_type;
  _count_type count;

   typedef double _brake_cmd_type;
  _brake_cmd_type brake_cmd;

   typedef double _throttle_cmd_type;
  _throttle_cmd_type throttle_cmd;

   typedef double _steering_cmd_front_wheel_type;
  _steering_cmd_front_wheel_type steering_cmd_front_wheel;

   typedef int16_t _gear_cmd_type;
  _gear_cmd_type gear_cmd;

   typedef int16_t _turn_signal_cmd_type;
  _turn_signal_cmd_type turn_signal_cmd;

   typedef double _speed_cmd_type;
  _speed_cmd_type speed_cmd;

   typedef double _acceleration_cmd_type;
  _acceleration_cmd_type acceleration_cmd;

   typedef int16_t _bywire_control_enable_type;
  _bywire_control_enable_type bywire_control_enable;

   typedef int16_t _emerg_brake_type;
  _emerg_brake_type emerg_brake;

   typedef int16_t _front_light_type;
  _front_light_type front_light;

   typedef int16_t _engine_enable_type;
  _engine_enable_type engine_enable;

   typedef int16_t _park_enable_type;
  _park_enable_type park_enable;

   typedef int16_t _vehicle_mode_type;
  _vehicle_mode_type vehicle_mode;

   typedef double _yaw_speed_cmd_type;
  _yaw_speed_cmd_type yaw_speed_cmd;

   typedef double _ey_out_type;
  _ey_out_type ey_out;

   typedef double _ephi_out_type;
  _ephi_out_type ephi_out;





  typedef boost::shared_ptr< ::cav_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::cav_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::cav_msgs::Control > ControlPtr;
typedef boost::shared_ptr< ::cav_msgs::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::Control_<ContainerAllocator1> & lhs, const ::cav_msgs::Control_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.count == rhs.count &&
    lhs.brake_cmd == rhs.brake_cmd &&
    lhs.throttle_cmd == rhs.throttle_cmd &&
    lhs.steering_cmd_front_wheel == rhs.steering_cmd_front_wheel &&
    lhs.gear_cmd == rhs.gear_cmd &&
    lhs.turn_signal_cmd == rhs.turn_signal_cmd &&
    lhs.speed_cmd == rhs.speed_cmd &&
    lhs.acceleration_cmd == rhs.acceleration_cmd &&
    lhs.bywire_control_enable == rhs.bywire_control_enable &&
    lhs.emerg_brake == rhs.emerg_brake &&
    lhs.front_light == rhs.front_light &&
    lhs.engine_enable == rhs.engine_enable &&
    lhs.park_enable == rhs.park_enable &&
    lhs.vehicle_mode == rhs.vehicle_mode &&
    lhs.yaw_speed_cmd == rhs.yaw_speed_cmd &&
    lhs.ey_out == rhs.ey_out &&
    lhs.ephi_out == rhs.ephi_out;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::Control_<ContainerAllocator1> & lhs, const ::cav_msgs::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4de11501bbe40ec65abb3e5c2250bd4d";
  }

  static const char* value(const ::cav_msgs::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4de11501bbe40ec6ULL;
  static const uint64_t static_value2 = 0x5abb3e5c2250bd4dULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/Control";
  }

  static const char* value(const ::cav_msgs::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "##timestamp\n"
"float64 timestamp 			#ros time\n"
"int32 	count               #1,2,3,4,5,...\n"
"\n"
"float64 brake_cmd 			#brake pedal opening [0-1, 100%]\n"
"float64 throttle_cmd 		#throttle pedal openning [0-1, 100%]\n"
"float64 steering_cmd_front_wheel #(-0.25pi to 0.25pi) rad, angle of front wheels\n"
"int16 	gear_cmd            # NONE:0, PARK:1, REVERSE:2, NEUTRAL:3, DRIVE:4, LOW:5\n"
"int16 	turn_signal_cmd     # NONE:0, LEFT:1, RIGHT:2\n"
"\n"
"float64 speed_cmd           #speed cmd, m/s\n"
"float64 acceleration_cmd    #acceleration cmd, m/s/s\n"
"\n"
"int16 bywire_control_enable #self-driving enabled, 0-off, 1-on\n"
"int16 emerg_brake           #0:normal brake, 1:emergency brake\n"
"int16 front_light           #0-off, 1-on\n"
"\n"
"int16 engine_enable         #0-off 1-on\n"
"int16 park_enable           #0-off, 1-on\n"
"int16 vehicle_mode          #0-pure EV, 1-Hybrid\n"
"float64 yaw_speed_cmd       #rad/s\n"
"\n"
"\n"
"##\n"
"float64 ey_out              #tracking error, lateral offset\n"
"float64 ephi_out            #tracking error, heading angle\n"
;
  }

  static const char* value(const ::cav_msgs::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.count);
      stream.next(m.brake_cmd);
      stream.next(m.throttle_cmd);
      stream.next(m.steering_cmd_front_wheel);
      stream.next(m.gear_cmd);
      stream.next(m.turn_signal_cmd);
      stream.next(m.speed_cmd);
      stream.next(m.acceleration_cmd);
      stream.next(m.bywire_control_enable);
      stream.next(m.emerg_brake);
      stream.next(m.front_light);
      stream.next(m.engine_enable);
      stream.next(m.park_enable);
      stream.next(m.vehicle_mode);
      stream.next(m.yaw_speed_cmd);
      stream.next(m.ey_out);
      stream.next(m.ephi_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::Control_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "brake_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.brake_cmd);
    s << indent << "throttle_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.throttle_cmd);
    s << indent << "steering_cmd_front_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.steering_cmd_front_wheel);
    s << indent << "gear_cmd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gear_cmd);
    s << indent << "turn_signal_cmd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.turn_signal_cmd);
    s << indent << "speed_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.speed_cmd);
    s << indent << "acceleration_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration_cmd);
    s << indent << "bywire_control_enable: ";
    Printer<int16_t>::stream(s, indent + "  ", v.bywire_control_enable);
    s << indent << "emerg_brake: ";
    Printer<int16_t>::stream(s, indent + "  ", v.emerg_brake);
    s << indent << "front_light: ";
    Printer<int16_t>::stream(s, indent + "  ", v.front_light);
    s << indent << "engine_enable: ";
    Printer<int16_t>::stream(s, indent + "  ", v.engine_enable);
    s << indent << "park_enable: ";
    Printer<int16_t>::stream(s, indent + "  ", v.park_enable);
    s << indent << "vehicle_mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vehicle_mode);
    s << indent << "yaw_speed_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_speed_cmd);
    s << indent << "ey_out: ";
    Printer<double>::stream(s, indent + "  ", v.ey_out);
    s << indent << "ephi_out: ";
    Printer<double>::stream(s, indent + "  ", v.ephi_out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_CONTROL_H
