// Generated by gencpp from file cav_msgs/Goal.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_GOAL_H
#define CAV_MSGS_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cav_msgs/RefPoint.h>

namespace cav_msgs
{
template <class ContainerAllocator>
struct Goal_
{
  typedef Goal_<ContainerAllocator> Type;

  Goal_()
    : timestamp(0.0)
    , Estop(0)
    , Go(false)
    , refPath()  {
    }
  Goal_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , Estop(0)
    , Go(false)
    , refPath(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int16_t _Estop_type;
  _Estop_type Estop;

   typedef uint8_t _Go_type;
  _Go_type Go;

   typedef std::vector< ::cav_msgs::RefPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cav_msgs::RefPoint_<ContainerAllocator> >> _refPath_type;
  _refPath_type refPath;





  typedef boost::shared_ptr< ::cav_msgs::Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::Goal_<ContainerAllocator> const> ConstPtr;

}; // struct Goal_

typedef ::cav_msgs::Goal_<std::allocator<void> > Goal;

typedef boost::shared_ptr< ::cav_msgs::Goal > GoalPtr;
typedef boost::shared_ptr< ::cav_msgs::Goal const> GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::Goal_<ContainerAllocator1> & lhs, const ::cav_msgs::Goal_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.Estop == rhs.Estop &&
    lhs.Go == rhs.Go &&
    lhs.refPath == rhs.refPath;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::Goal_<ContainerAllocator1> & lhs, const ::cav_msgs::Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Goal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5512e5dddfea9dde6ed8bf22e640c5e2";
  }

  static const char* value(const ::cav_msgs::Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5512e5dddfea9ddeULL;
  static const uint64_t static_value2 = 0x6ed8bf22e640c5e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/Goal";
  }

  static const char* value(const ::cav_msgs::Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"##timestamp, ros time or utc time\n"
"float64     timestamp\n"
"\n"
"#part 1: direct commands\n"
"int16 	Estop    # 0:none  1:low  2:medium   3:high\n"
"bool 	Go       # false, true\n"
"\n"
"#part 2 -- lane center and drivable area\n"
"RefPoint[] refPath\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cav_msgs/RefPoint\n"
"#reference path\n"
"float64 t   # time of this point\n"
"float64 x\n"
"float64 y\n"
"float64 v\n"
"float64 heading\n"
"float64 cr\n"
"\n"
"#drivable area\n"
"float64 	left_width\n"
"float64 	right_width\n"
;
  }

  static const char* value(const ::cav_msgs::Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.Estop);
      stream.next(m.Go);
      stream.next(m.refPath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::Goal_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "Estop: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Estop);
    s << indent << "Go: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Go);
    s << indent << "refPath[]" << std::endl;
    for (size_t i = 0; i < v.refPath.size(); ++i)
    {
      s << indent << "  refPath[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cav_msgs::RefPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.refPath[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_GOAL_H
