// Generated by gencpp from file cav_msgs/Gpybm.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_GPYBM_H
#define CAV_MSGS_MESSAGE_GPYBM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cav_msgs
{
template <class ContainerAllocator>
struct Gpybm_
{
  typedef Gpybm_<ContainerAllocator> Type;

  Gpybm_()
    : serial_number()
    , utc(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , north_vel(0.0)
    , east_vel(0.0)
    , earth_vel(0.0)
    , vel(0.0)
    , gaussian_x(0.0)
    , gaussian_y(0.0)
    , base_station_x(0.0)
    , base_station_y(0.0)
    , status(0)
    , status_vice(0)  {
    }
  Gpybm_(const ContainerAllocator& _alloc)
    : serial_number(_alloc)
    , utc(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , north_vel(0.0)
    , east_vel(0.0)
    , earth_vel(0.0)
    , vel(0.0)
    , gaussian_x(0.0)
    , gaussian_y(0.0)
    , base_station_x(0.0)
    , base_station_y(0.0)
    , status(0)
    , status_vice(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _serial_number_type;
  _serial_number_type serial_number;

   typedef double _utc_type;
  _utc_type utc;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_type;
  _height_type height;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _north_vel_type;
  _north_vel_type north_vel;

   typedef double _east_vel_type;
  _east_vel_type east_vel;

   typedef double _earth_vel_type;
  _earth_vel_type earth_vel;

   typedef double _vel_type;
  _vel_type vel;

   typedef double _gaussian_x_type;
  _gaussian_x_type gaussian_x;

   typedef double _gaussian_y_type;
  _gaussian_y_type gaussian_y;

   typedef double _base_station_x_type;
  _base_station_x_type base_station_x;

   typedef double _base_station_y_type;
  _base_station_y_type base_station_y;

   typedef int16_t _status_type;
  _status_type status;

   typedef int16_t _status_vice_type;
  _status_vice_type status_vice;





  typedef boost::shared_ptr< ::cav_msgs::Gpybm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::Gpybm_<ContainerAllocator> const> ConstPtr;

}; // struct Gpybm_

typedef ::cav_msgs::Gpybm_<std::allocator<void> > Gpybm;

typedef boost::shared_ptr< ::cav_msgs::Gpybm > GpybmPtr;
typedef boost::shared_ptr< ::cav_msgs::Gpybm const> GpybmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::Gpybm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::Gpybm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::Gpybm_<ContainerAllocator1> & lhs, const ::cav_msgs::Gpybm_<ContainerAllocator2> & rhs)
{
  return lhs.serial_number == rhs.serial_number &&
    lhs.utc == rhs.utc &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.height == rhs.height &&
    lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.north_vel == rhs.north_vel &&
    lhs.east_vel == rhs.east_vel &&
    lhs.earth_vel == rhs.earth_vel &&
    lhs.vel == rhs.vel &&
    lhs.gaussian_x == rhs.gaussian_x &&
    lhs.gaussian_y == rhs.gaussian_y &&
    lhs.base_station_x == rhs.base_station_x &&
    lhs.base_station_y == rhs.base_station_y &&
    lhs.status == rhs.status &&
    lhs.status_vice == rhs.status_vice;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::Gpybm_<ContainerAllocator1> & lhs, const ::cav_msgs::Gpybm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Gpybm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Gpybm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Gpybm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Gpybm_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Gpybm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Gpybm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::Gpybm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705e6b1ef5c61da21386f82da44e4cfd";
  }

  static const char* value(const ::cav_msgs::Gpybm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705e6b1ef5c61da2ULL;
  static const uint64_t static_value2 = 0x1386f82da44e4cfdULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::Gpybm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/Gpybm";
  }

  static const char* value(const ::cav_msgs::Gpybm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::Gpybm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string serial_number # sino gnss hardware serial number\n"
"float64 utc       # utc time\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 height\n"
"\n"
"float64 yaw\n"
"float64 pitch  \n"
"float64 north_vel\n"
"float64 east_vel\n"
"float64 earth_vel\n"
"float64 vel\n"
"float64 gaussian_x\n"
"float64 gaussian_y\n"
"float64 base_station_x\n"
"float64 base_station_y\n"
"\n"
"int16 status	\n"
"int16 status_vice\n"
"\n"
;
  }

  static const char* value(const ::cav_msgs::Gpybm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::Gpybm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serial_number);
      stream.next(m.utc);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.north_vel);
      stream.next(m.east_vel);
      stream.next(m.earth_vel);
      stream.next(m.vel);
      stream.next(m.gaussian_x);
      stream.next(m.gaussian_y);
      stream.next(m.base_station_x);
      stream.next(m.base_station_y);
      stream.next(m.status);
      stream.next(m.status_vice);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gpybm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::Gpybm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::Gpybm_<ContainerAllocator>& v)
  {
    s << indent << "serial_number: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.serial_number);
    s << indent << "utc: ";
    Printer<double>::stream(s, indent + "  ", v.utc);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "north_vel: ";
    Printer<double>::stream(s, indent + "  ", v.north_vel);
    s << indent << "east_vel: ";
    Printer<double>::stream(s, indent + "  ", v.east_vel);
    s << indent << "earth_vel: ";
    Printer<double>::stream(s, indent + "  ", v.earth_vel);
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "gaussian_x: ";
    Printer<double>::stream(s, indent + "  ", v.gaussian_x);
    s << indent << "gaussian_y: ";
    Printer<double>::stream(s, indent + "  ", v.gaussian_y);
    s << indent << "base_station_x: ";
    Printer<double>::stream(s, indent + "  ", v.base_station_x);
    s << indent << "base_station_y: ";
    Printer<double>::stream(s, indent + "  ", v.base_station_y);
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
    s << indent << "status_vice: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status_vice);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_GPYBM_H
