// Generated by gencpp from file cav_msgs/Obstacle.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_OBSTACLE_H
#define CAV_MSGS_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cav_msgs
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : timestamp(0.0)
    , id(0)
    , type(0)
    , radius(0.0)
    , x_global(0.0)
    , y_global(0.0)
    , speed_x(0.0)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , id(0)
    , type(0)
    , radius(0.0)
    , x_global(0.0)
    , y_global(0.0)
    , speed_x(0.0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _id_type;
  _id_type id;

   typedef int16_t _type_type;
  _type_type type;

   typedef double _radius_type;
  _radius_type radius;

   typedef double _x_global_type;
  _x_global_type x_global;

   typedef double _y_global_type;
  _y_global_type y_global;

   typedef double _speed_x_type;
  _speed_x_type speed_x;





  typedef boost::shared_ptr< ::cav_msgs::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::cav_msgs::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::cav_msgs::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::cav_msgs::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::cav_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.radius == rhs.radius &&
    lhs.x_global == rhs.x_global &&
    lhs.y_global == rhs.y_global &&
    lhs.speed_x == rhs.speed_x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::Obstacle_<ContainerAllocator1> & lhs, const ::cav_msgs::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a54a7e58941fdabf5915ce1f4cd97ed5";
  }

  static const char* value(const ::cav_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa54a7e58941fdabfULL;
  static const uint64_t static_value2 = 0x5915ce1f4cd97ed5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/Obstacle";
  }

  static const char* value(const ::cav_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 	timestamp   #ros time\n"
"int32 		id\n"
"int16 		type        #refer to below definition       \n"
"float64     radius      # m, radius for object circle\n"
"\n"
"float64 	x_global   #m, in the same coordinate system of the ego car\n"
"float64 	y_global   #m, in the same coordinate system of the ego car\n"
"\n"
"float64 	speed_x    #not official definition\n"
;
  }

  static const char* value(const ::cav_msgs::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.radius);
      stream.next(m.x_global);
      stream.next(m.y_global);
      stream.next(m.speed_x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.type);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
    s << indent << "x_global: ";
    Printer<double>::stream(s, indent + "  ", v.x_global);
    s << indent << "y_global: ";
    Printer<double>::stream(s, indent + "  ", v.y_global);
    s << indent << "speed_x: ";
    Printer<double>::stream(s, indent + "  ", v.speed_x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_OBSTACLE_H
