// Generated by gencpp from file cav_msgs/ObstacleVec.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_OBSTACLEVEC_H
#define CAV_MSGS_MESSAGE_OBSTACLEVEC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cav_msgs/Obstacle.h>

namespace cav_msgs
{
template <class ContainerAllocator>
struct ObstacleVec_
{
  typedef ObstacleVec_<ContainerAllocator> Type;

  ObstacleVec_()
    : timestamp(0.0)
    , len(0)
    , obstacleVec()  {
    }
  ObstacleVec_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , len(0)
    , obstacleVec(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _len_type;
  _len_type len;

   typedef std::vector< ::cav_msgs::Obstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cav_msgs::Obstacle_<ContainerAllocator> >> _obstacleVec_type;
  _obstacleVec_type obstacleVec;





  typedef boost::shared_ptr< ::cav_msgs::ObstacleVec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::ObstacleVec_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleVec_

typedef ::cav_msgs::ObstacleVec_<std::allocator<void> > ObstacleVec;

typedef boost::shared_ptr< ::cav_msgs::ObstacleVec > ObstacleVecPtr;
typedef boost::shared_ptr< ::cav_msgs::ObstacleVec const> ObstacleVecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::ObstacleVec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::ObstacleVec_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::ObstacleVec_<ContainerAllocator1> & lhs, const ::cav_msgs::ObstacleVec_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.len == rhs.len &&
    lhs.obstacleVec == rhs.obstacleVec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::ObstacleVec_<ContainerAllocator1> & lhs, const ::cav_msgs::ObstacleVec_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::ObstacleVec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::ObstacleVec_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::ObstacleVec_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60d3a37403fa2a27da845f05fbc1cd50";
  }

  static const char* value(const ::cav_msgs::ObstacleVec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60d3a37403fa2a27ULL;
  static const uint64_t static_value2 = 0xda845f05fbc1cd50ULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/ObstacleVec";
  }

  static const char* value(const ::cav_msgs::ObstacleVec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 	timestamp\n"
"int32   	len\n"
"Obstacle[]   	obstacleVec\n"
"\n"
"================================================================================\n"
"MSG: cav_msgs/Obstacle\n"
"float64 	timestamp   #ros time\n"
"int32 		id\n"
"int16 		type        #refer to below definition       \n"
"float64     radius      # m, radius for object circle\n"
"\n"
"float64 	x_global   #m, in the same coordinate system of the ego car\n"
"float64 	y_global   #m, in the same coordinate system of the ego car\n"
"\n"
"float64 	speed_x    #not official definition\n"
;
  }

  static const char* value(const ::cav_msgs::ObstacleVec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.len);
      stream.next(m.obstacleVec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleVec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::ObstacleVec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::ObstacleVec_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "len: ";
    Printer<int32_t>::stream(s, indent + "  ", v.len);
    s << indent << "obstacleVec[]" << std::endl;
    for (size_t i = 0; i < v.obstacleVec.size(); ++i)
    {
      s << indent << "  obstacleVec[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cav_msgs::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacleVec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_OBSTACLEVEC_H
