// Generated by gencpp from file cav_msgs/PlanedPath.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_PLANEDPATH_H
#define CAV_MSGS_MESSAGE_PLANEDPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cav_msgs/Point.h>

namespace cav_msgs
{
template <class ContainerAllocator>
struct PlanedPath_
{
  typedef PlanedPath_<ContainerAllocator> Type;

  PlanedPath_()
    : timestamp(0.0)
    , Go(false)
    , Estop(0)
    , forward_flag(false)
    , backward_flag(false)
    , planedPath()  {
    }
  PlanedPath_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , Go(false)
    , Estop(0)
    , forward_flag(false)
    , backward_flag(false)
    , planedPath(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _Go_type;
  _Go_type Go;

   typedef int16_t _Estop_type;
  _Estop_type Estop;

   typedef uint8_t _forward_flag_type;
  _forward_flag_type forward_flag;

   typedef uint8_t _backward_flag_type;
  _backward_flag_type backward_flag;

   typedef std::vector< ::cav_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cav_msgs::Point_<ContainerAllocator> >> _planedPath_type;
  _planedPath_type planedPath;





  typedef boost::shared_ptr< ::cav_msgs::PlanedPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::PlanedPath_<ContainerAllocator> const> ConstPtr;

}; // struct PlanedPath_

typedef ::cav_msgs::PlanedPath_<std::allocator<void> > PlanedPath;

typedef boost::shared_ptr< ::cav_msgs::PlanedPath > PlanedPathPtr;
typedef boost::shared_ptr< ::cav_msgs::PlanedPath const> PlanedPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::PlanedPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::PlanedPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::PlanedPath_<ContainerAllocator1> & lhs, const ::cav_msgs::PlanedPath_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.Go == rhs.Go &&
    lhs.Estop == rhs.Estop &&
    lhs.forward_flag == rhs.forward_flag &&
    lhs.backward_flag == rhs.backward_flag &&
    lhs.planedPath == rhs.planedPath;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::PlanedPath_<ContainerAllocator1> & lhs, const ::cav_msgs::PlanedPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::PlanedPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::PlanedPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::PlanedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::PlanedPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::PlanedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::PlanedPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::PlanedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c81ebe469d3c8540c20f292a56d467d8";
  }

  static const char* value(const ::cav_msgs::PlanedPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc81ebe469d3c8540ULL;
  static const uint64_t static_value2 = 0xc20f292a56d467d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::PlanedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/PlanedPath";
  }

  static const char* value(const ::cav_msgs::PlanedPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::PlanedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 timestamp   # ROS time in seconds\n"
"bool 	Go          # false, true\n"
"int16   Estop       # 0:none  1:low  2:medium   3:high\n"
"\n"
"# move forward or backward, both of them should be set to ensure safety\n"
"bool forward_flag       #true\n"
"bool backward_flag      #false\n"
"\n"
"# note that all of the vectors should be set\n"
"# t: must be 0.04 seconds per point, i.e., 25 points per second\n"
"# x: degree, in global GNSS frame\n"
"# y: degree, in global GNSS frame\n"
"# v: vector of desired speed m/s\n"
"# heading: vector of heading info, rad, north: pi/2, east:0\n"
"# cr: curvature, note + or - for each element\n"
"Point[] planedPath\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cav_msgs/Point\n"
"float64 t   # time of this point\n"
"float64 x\n"
"float64 y\n"
"float64 v\n"
"float64 heading\n"
"float64 cr\n"
;
  }

  static const char* value(const ::cav_msgs::PlanedPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::PlanedPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.Go);
      stream.next(m.Estop);
      stream.next(m.forward_flag);
      stream.next(m.backward_flag);
      stream.next(m.planedPath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanedPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::PlanedPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::PlanedPath_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "Go: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Go);
    s << indent << "Estop: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Estop);
    s << indent << "forward_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward_flag);
    s << indent << "backward_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.backward_flag);
    s << indent << "planedPath[]" << std::endl;
    for (size_t i = 0; i < v.planedPath.size(); ++i)
    {
      s << indent << "  planedPath[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cav_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.planedPath[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_PLANEDPATH_H
