// Generated by gencpp from file cav_msgs/RefPoint.msg
// DO NOT EDIT!


#ifndef CAV_MSGS_MESSAGE_REFPOINT_H
#define CAV_MSGS_MESSAGE_REFPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cav_msgs
{
template <class ContainerAllocator>
struct RefPoint_
{
  typedef RefPoint_<ContainerAllocator> Type;

  RefPoint_()
    : t(0.0)
    , x(0.0)
    , y(0.0)
    , v(0.0)
    , heading(0.0)
    , cr(0.0)
    , left_width(0.0)
    , right_width(0.0)  {
    }
  RefPoint_(const ContainerAllocator& _alloc)
    : t(0.0)
    , x(0.0)
    , y(0.0)
    , v(0.0)
    , heading(0.0)
    , cr(0.0)
    , left_width(0.0)
    , right_width(0.0)  {
  (void)_alloc;
    }



   typedef double _t_type;
  _t_type t;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _v_type;
  _v_type v;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _cr_type;
  _cr_type cr;

   typedef double _left_width_type;
  _left_width_type left_width;

   typedef double _right_width_type;
  _right_width_type right_width;





  typedef boost::shared_ptr< ::cav_msgs::RefPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_msgs::RefPoint_<ContainerAllocator> const> ConstPtr;

}; // struct RefPoint_

typedef ::cav_msgs::RefPoint_<std::allocator<void> > RefPoint;

typedef boost::shared_ptr< ::cav_msgs::RefPoint > RefPointPtr;
typedef boost::shared_ptr< ::cav_msgs::RefPoint const> RefPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_msgs::RefPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_msgs::RefPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_msgs::RefPoint_<ContainerAllocator1> & lhs, const ::cav_msgs::RefPoint_<ContainerAllocator2> & rhs)
{
  return lhs.t == rhs.t &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.v == rhs.v &&
    lhs.heading == rhs.heading &&
    lhs.cr == rhs.cr &&
    lhs.left_width == rhs.left_width &&
    lhs.right_width == rhs.right_width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_msgs::RefPoint_<ContainerAllocator1> & lhs, const ::cav_msgs::RefPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::RefPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_msgs::RefPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::RefPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_msgs::RefPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::RefPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_msgs::RefPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_msgs::RefPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4578623091705a57837c7e08dd996a1f";
  }

  static const char* value(const ::cav_msgs::RefPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4578623091705a57ULL;
  static const uint64_t static_value2 = 0x837c7e08dd996a1fULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_msgs::RefPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_msgs/RefPoint";
  }

  static const char* value(const ::cav_msgs::RefPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_msgs::RefPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#reference path\n"
"float64 t   # time of this point\n"
"float64 x\n"
"float64 y\n"
"float64 v\n"
"float64 heading\n"
"float64 cr\n"
"\n"
"#drivable area\n"
"float64 	left_width\n"
"float64 	right_width\n"
;
  }

  static const char* value(const ::cav_msgs::RefPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_msgs::RefPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.v);
      stream.next(m.heading);
      stream.next(m.cr);
      stream.next(m.left_width);
      stream.next(m.right_width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RefPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_msgs::RefPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_msgs::RefPoint_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "cr: ";
    Printer<double>::stream(s, indent + "  ", v.cr);
    s << indent << "left_width: ";
    Printer<double>::stream(s, indent + "  ", v.left_width);
    s << indent << "right_width: ";
    Printer<double>::stream(s, indent + "  ", v.right_width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_MSGS_MESSAGE_REFPOINT_H
