# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/Control.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Control(genpy.Message):
  _md5sum = "4de11501bbe40ec65abb3e5c2250bd4d"
  _type = "cav_msgs/Control"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """##timestamp
float64 timestamp 			#ros time
int32 	count               #1,2,3,4,5,...

float64 brake_cmd 			#brake pedal opening [0-1, 100%]
float64 throttle_cmd 		#throttle pedal openning [0-1, 100%]
float64 steering_cmd_front_wheel #(-0.25pi to 0.25pi) rad, angle of front wheels
int16 	gear_cmd            # NONE:0, PARK:1, REVERSE:2, NEUTRAL:3, DRIVE:4, LOW:5
int16 	turn_signal_cmd     # NONE:0, LEFT:1, RIGHT:2

float64 speed_cmd           #speed cmd, m/s
float64 acceleration_cmd    #acceleration cmd, m/s/s

int16 bywire_control_enable #self-driving enabled, 0-off, 1-on
int16 emerg_brake           #0:normal brake, 1:emergency brake
int16 front_light           #0-off, 1-on

int16 engine_enable         #0-off 1-on
int16 park_enable           #0-off, 1-on
int16 vehicle_mode          #0-pure EV, 1-Hybrid
float64 yaw_speed_cmd       #rad/s


##
float64 ey_out              #tracking error, lateral offset
float64 ephi_out            #tracking error, heading angle
"""
  __slots__ = ['timestamp','count','brake_cmd','throttle_cmd','steering_cmd_front_wheel','gear_cmd','turn_signal_cmd','speed_cmd','acceleration_cmd','bywire_control_enable','emerg_brake','front_light','engine_enable','park_enable','vehicle_mode','yaw_speed_cmd','ey_out','ephi_out']
  _slot_types = ['float64','int32','float64','float64','float64','int16','int16','float64','float64','int16','int16','int16','int16','int16','int16','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,count,brake_cmd,throttle_cmd,steering_cmd_front_wheel,gear_cmd,turn_signal_cmd,speed_cmd,acceleration_cmd,bywire_control_enable,emerg_brake,front_light,engine_enable,park_enable,vehicle_mode,yaw_speed_cmd,ey_out,ephi_out

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Control, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.count is None:
        self.count = 0
      if self.brake_cmd is None:
        self.brake_cmd = 0.
      if self.throttle_cmd is None:
        self.throttle_cmd = 0.
      if self.steering_cmd_front_wheel is None:
        self.steering_cmd_front_wheel = 0.
      if self.gear_cmd is None:
        self.gear_cmd = 0
      if self.turn_signal_cmd is None:
        self.turn_signal_cmd = 0
      if self.speed_cmd is None:
        self.speed_cmd = 0.
      if self.acceleration_cmd is None:
        self.acceleration_cmd = 0.
      if self.bywire_control_enable is None:
        self.bywire_control_enable = 0
      if self.emerg_brake is None:
        self.emerg_brake = 0
      if self.front_light is None:
        self.front_light = 0
      if self.engine_enable is None:
        self.engine_enable = 0
      if self.park_enable is None:
        self.park_enable = 0
      if self.vehicle_mode is None:
        self.vehicle_mode = 0
      if self.yaw_speed_cmd is None:
        self.yaw_speed_cmd = 0.
      if self.ey_out is None:
        self.ey_out = 0.
      if self.ephi_out is None:
        self.ephi_out = 0.
    else:
      self.timestamp = 0.
      self.count = 0
      self.brake_cmd = 0.
      self.throttle_cmd = 0.
      self.steering_cmd_front_wheel = 0.
      self.gear_cmd = 0
      self.turn_signal_cmd = 0
      self.speed_cmd = 0.
      self.acceleration_cmd = 0.
      self.bywire_control_enable = 0
      self.emerg_brake = 0
      self.front_light = 0
      self.engine_enable = 0
      self.park_enable = 0
      self.vehicle_mode = 0
      self.yaw_speed_cmd = 0.
      self.ey_out = 0.
      self.ephi_out = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_di3d2h2d6h3d().pack(_x.timestamp, _x.count, _x.brake_cmd, _x.throttle_cmd, _x.steering_cmd_front_wheel, _x.gear_cmd, _x.turn_signal_cmd, _x.speed_cmd, _x.acceleration_cmd, _x.bywire_control_enable, _x.emerg_brake, _x.front_light, _x.engine_enable, _x.park_enable, _x.vehicle_mode, _x.yaw_speed_cmd, _x.ey_out, _x.ephi_out))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 92
      (_x.timestamp, _x.count, _x.brake_cmd, _x.throttle_cmd, _x.steering_cmd_front_wheel, _x.gear_cmd, _x.turn_signal_cmd, _x.speed_cmd, _x.acceleration_cmd, _x.bywire_control_enable, _x.emerg_brake, _x.front_light, _x.engine_enable, _x.park_enable, _x.vehicle_mode, _x.yaw_speed_cmd, _x.ey_out, _x.ephi_out,) = _get_struct_di3d2h2d6h3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_di3d2h2d6h3d().pack(_x.timestamp, _x.count, _x.brake_cmd, _x.throttle_cmd, _x.steering_cmd_front_wheel, _x.gear_cmd, _x.turn_signal_cmd, _x.speed_cmd, _x.acceleration_cmd, _x.bywire_control_enable, _x.emerg_brake, _x.front_light, _x.engine_enable, _x.park_enable, _x.vehicle_mode, _x.yaw_speed_cmd, _x.ey_out, _x.ephi_out))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 92
      (_x.timestamp, _x.count, _x.brake_cmd, _x.throttle_cmd, _x.steering_cmd_front_wheel, _x.gear_cmd, _x.turn_signal_cmd, _x.speed_cmd, _x.acceleration_cmd, _x.bywire_control_enable, _x.emerg_brake, _x.front_light, _x.engine_enable, _x.park_enable, _x.vehicle_mode, _x.yaw_speed_cmd, _x.ey_out, _x.ephi_out,) = _get_struct_di3d2h2d6h3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_di3d2h2d6h3d = None
def _get_struct_di3d2h2d6h3d():
    global _struct_di3d2h2d6h3d
    if _struct_di3d2h2d6h3d is None:
        _struct_di3d2h2d6h3d = struct.Struct("<di3d2h2d6h3d")
    return _struct_di3d2h2d6h3d
