# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/Goal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cav_msgs.msg

class Goal(genpy.Message):
  _md5sum = "5512e5dddfea9dde6ed8bf22e640c5e2"
  _type = "cav_msgs/Goal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
##timestamp, ros time or utc time
float64     timestamp

#part 1: direct commands
int16 	Estop    # 0:none  1:low  2:medium   3:high
bool 	Go       # false, true

#part 2 -- lane center and drivable area
RefPoint[] refPath


================================================================================
MSG: cav_msgs/RefPoint
#reference path
float64 t   # time of this point
float64 x
float64 y
float64 v
float64 heading
float64 cr

#drivable area
float64 	left_width
float64 	right_width"""
  __slots__ = ['timestamp','Estop','Go','refPath']
  _slot_types = ['float64','int16','bool','cav_msgs/RefPoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,Estop,Go,refPath

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Goal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.Estop is None:
        self.Estop = 0
      if self.Go is None:
        self.Go = False
      if self.refPath is None:
        self.refPath = []
    else:
      self.timestamp = 0.
      self.Estop = 0
      self.Go = False
      self.refPath = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dhB().pack(_x.timestamp, _x.Estop, _x.Go))
      length = len(self.refPath)
      buff.write(_struct_I.pack(length))
      for val1 in self.refPath:
        _x = val1
        buff.write(_get_struct_8d().pack(_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.refPath is None:
        self.refPath = None
      end = 0
      _x = self
      start = end
      end += 11
      (_x.timestamp, _x.Estop, _x.Go,) = _get_struct_dhB().unpack(str[start:end])
      self.Go = bool(self.Go)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.refPath = []
      for i in range(0, length):
        val1 = cav_msgs.msg.RefPoint()
        _x = val1
        start = end
        end += 64
        (_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width,) = _get_struct_8d().unpack(str[start:end])
        self.refPath.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dhB().pack(_x.timestamp, _x.Estop, _x.Go))
      length = len(self.refPath)
      buff.write(_struct_I.pack(length))
      for val1 in self.refPath:
        _x = val1
        buff.write(_get_struct_8d().pack(_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.refPath is None:
        self.refPath = None
      end = 0
      _x = self
      start = end
      end += 11
      (_x.timestamp, _x.Estop, _x.Go,) = _get_struct_dhB().unpack(str[start:end])
      self.Go = bool(self.Go)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.refPath = []
      for i in range(0, length):
        val1 = cav_msgs.msg.RefPoint()
        _x = val1
        start = end
        end += 64
        (_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width,) = _get_struct_8d().unpack(str[start:end])
        self.refPath.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
_struct_dhB = None
def _get_struct_dhB():
    global _struct_dhB
    if _struct_dhB is None:
        _struct_dhB = struct.Struct("<dhB")
    return _struct_dhB
