# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/Gpybm.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Gpybm(genpy.Message):
  _md5sum = "705e6b1ef5c61da21386f82da44e4cfd"
  _type = "cav_msgs/Gpybm"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string serial_number # sino gnss hardware serial number
float64 utc       # utc time
float64 latitude
float64 longitude
float64 height

float64 yaw
float64 pitch  
float64 north_vel
float64 east_vel
float64 earth_vel
float64 vel
float64 gaussian_x
float64 gaussian_y
float64 base_station_x
float64 base_station_y

int16 status	
int16 status_vice

"""
  __slots__ = ['serial_number','utc','latitude','longitude','height','yaw','pitch','north_vel','east_vel','earth_vel','vel','gaussian_x','gaussian_y','base_station_x','base_station_y','status','status_vice']
  _slot_types = ['string','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       serial_number,utc,latitude,longitude,height,yaw,pitch,north_vel,east_vel,earth_vel,vel,gaussian_x,gaussian_y,base_station_x,base_station_y,status,status_vice

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Gpybm, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.serial_number is None:
        self.serial_number = ''
      if self.utc is None:
        self.utc = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.height is None:
        self.height = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.north_vel is None:
        self.north_vel = 0.
      if self.east_vel is None:
        self.east_vel = 0.
      if self.earth_vel is None:
        self.earth_vel = 0.
      if self.vel is None:
        self.vel = 0.
      if self.gaussian_x is None:
        self.gaussian_x = 0.
      if self.gaussian_y is None:
        self.gaussian_y = 0.
      if self.base_station_x is None:
        self.base_station_x = 0.
      if self.base_station_y is None:
        self.base_station_y = 0.
      if self.status is None:
        self.status = 0
      if self.status_vice is None:
        self.status_vice = 0
    else:
      self.serial_number = ''
      self.utc = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.height = 0.
      self.yaw = 0.
      self.pitch = 0.
      self.north_vel = 0.
      self.east_vel = 0.
      self.earth_vel = 0.
      self.vel = 0.
      self.gaussian_x = 0.
      self.gaussian_y = 0.
      self.base_station_x = 0.
      self.base_station_y = 0.
      self.status = 0
      self.status_vice = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.serial_number
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d2h().pack(_x.utc, _x.latitude, _x.longitude, _x.height, _x.yaw, _x.pitch, _x.north_vel, _x.east_vel, _x.earth_vel, _x.vel, _x.gaussian_x, _x.gaussian_y, _x.base_station_x, _x.base_station_y, _x.status, _x.status_vice))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.serial_number = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.serial_number = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.utc, _x.latitude, _x.longitude, _x.height, _x.yaw, _x.pitch, _x.north_vel, _x.east_vel, _x.earth_vel, _x.vel, _x.gaussian_x, _x.gaussian_y, _x.base_station_x, _x.base_station_y, _x.status, _x.status_vice,) = _get_struct_14d2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.serial_number
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d2h().pack(_x.utc, _x.latitude, _x.longitude, _x.height, _x.yaw, _x.pitch, _x.north_vel, _x.east_vel, _x.earth_vel, _x.vel, _x.gaussian_x, _x.gaussian_y, _x.base_station_x, _x.base_station_y, _x.status, _x.status_vice))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.serial_number = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.serial_number = str[start:end]
      _x = self
      start = end
      end += 116
      (_x.utc, _x.latitude, _x.longitude, _x.height, _x.yaw, _x.pitch, _x.north_vel, _x.east_vel, _x.earth_vel, _x.vel, _x.gaussian_x, _x.gaussian_y, _x.base_station_x, _x.base_station_y, _x.status, _x.status_vice,) = _get_struct_14d2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14d2h = None
def _get_struct_14d2h():
    global _struct_14d2h
    if _struct_14d2h is None:
        _struct_14d2h = struct.Struct("<14d2h")
    return _struct_14d2h
