# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/Obstacle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Obstacle(genpy.Message):
  _md5sum = "a54a7e58941fdabf5915ce1f4cd97ed5"
  _type = "cav_msgs/Obstacle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 	timestamp   #ros time
int32 		id
int16 		type        #refer to below definition       
float64     radius      # m, radius for object circle

float64 	x_global   #m, in the same coordinate system of the ego car
float64 	y_global   #m, in the same coordinate system of the ego car

float64 	speed_x    #not official definition
"""
  __slots__ = ['timestamp','id','type','radius','x_global','y_global','speed_x']
  _slot_types = ['float64','int32','int16','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,id,type,radius,x_global,y_global,speed_x

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Obstacle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.id is None:
        self.id = 0
      if self.type is None:
        self.type = 0
      if self.radius is None:
        self.radius = 0.
      if self.x_global is None:
        self.x_global = 0.
      if self.y_global is None:
        self.y_global = 0.
      if self.speed_x is None:
        self.speed_x = 0.
    else:
      self.timestamp = 0.
      self.id = 0
      self.type = 0
      self.radius = 0.
      self.x_global = 0.
      self.y_global = 0.
      self.speed_x = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dih4d().pack(_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 46
      (_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x,) = _get_struct_dih4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dih4d().pack(_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 46
      (_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x,) = _get_struct_dih4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dih4d = None
def _get_struct_dih4d():
    global _struct_dih4d
    if _struct_dih4d is None:
        _struct_dih4d = struct.Struct("<dih4d")
    return _struct_dih4d
