# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/ObstacleVec.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cav_msgs.msg

class ObstacleVec(genpy.Message):
  _md5sum = "60d3a37403fa2a27da845f05fbc1cd50"
  _type = "cav_msgs/ObstacleVec"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
float64 	timestamp
int32   	len
Obstacle[]   	obstacleVec

================================================================================
MSG: cav_msgs/Obstacle
float64 	timestamp   #ros time
int32 		id
int16 		type        #refer to below definition       
float64     radius      # m, radius for object circle

float64 	x_global   #m, in the same coordinate system of the ego car
float64 	y_global   #m, in the same coordinate system of the ego car

float64 	speed_x    #not official definition
"""
  __slots__ = ['timestamp','len','obstacleVec']
  _slot_types = ['float64','int32','cav_msgs/Obstacle[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,len,obstacleVec

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstacleVec, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.len is None:
        self.len = 0
      if self.obstacleVec is None:
        self.obstacleVec = []
    else:
      self.timestamp = 0.
      self.len = 0
      self.obstacleVec = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_di().pack(_x.timestamp, _x.len))
      length = len(self.obstacleVec)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacleVec:
        _x = val1
        buff.write(_get_struct_dih4d().pack(_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obstacleVec is None:
        self.obstacleVec = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.timestamp, _x.len,) = _get_struct_di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacleVec = []
      for i in range(0, length):
        val1 = cav_msgs.msg.Obstacle()
        _x = val1
        start = end
        end += 46
        (_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x,) = _get_struct_dih4d().unpack(str[start:end])
        self.obstacleVec.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_di().pack(_x.timestamp, _x.len))
      length = len(self.obstacleVec)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacleVec:
        _x = val1
        buff.write(_get_struct_dih4d().pack(_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obstacleVec is None:
        self.obstacleVec = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.timestamp, _x.len,) = _get_struct_di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacleVec = []
      for i in range(0, length):
        val1 = cav_msgs.msg.Obstacle()
        _x = val1
        start = end
        end += 46
        (_x.timestamp, _x.id, _x.type, _x.radius, _x.x_global, _x.y_global, _x.speed_x,) = _get_struct_dih4d().unpack(str[start:end])
        self.obstacleVec.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_di = None
def _get_struct_di():
    global _struct_di
    if _struct_di is None:
        _struct_di = struct.Struct("<di")
    return _struct_di
_struct_dih4d = None
def _get_struct_dih4d():
    global _struct_dih4d
    if _struct_dih4d is None:
        _struct_dih4d = struct.Struct("<dih4d")
    return _struct_dih4d
