# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/PlanedPath.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cav_msgs.msg

class PlanedPath(genpy.Message):
  _md5sum = "c81ebe469d3c8540c20f292a56d467d8"
  _type = "cav_msgs/PlanedPath"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
float64 timestamp   # ROS time in seconds
bool 	Go          # false, true
int16   Estop       # 0:none  1:low  2:medium   3:high

# move forward or backward, both of them should be set to ensure safety
bool forward_flag       #true
bool backward_flag      #false

# note that all of the vectors should be set
# t: must be 0.04 seconds per point, i.e., 25 points per second
# x: degree, in global GNSS frame
# y: degree, in global GNSS frame
# v: vector of desired speed m/s
# heading: vector of heading info, rad, north: pi/2, east:0
# cr: curvature, note + or - for each element
Point[] planedPath




================================================================================
MSG: cav_msgs/Point
float64 t   # time of this point
float64 x
float64 y
float64 v
float64 heading
float64 cr"""
  __slots__ = ['timestamp','Go','Estop','forward_flag','backward_flag','planedPath']
  _slot_types = ['float64','bool','int16','bool','bool','cav_msgs/Point[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,Go,Estop,forward_flag,backward_flag,planedPath

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanedPath, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.Go is None:
        self.Go = False
      if self.Estop is None:
        self.Estop = 0
      if self.forward_flag is None:
        self.forward_flag = False
      if self.backward_flag is None:
        self.backward_flag = False
      if self.planedPath is None:
        self.planedPath = []
    else:
      self.timestamp = 0.
      self.Go = False
      self.Estop = 0
      self.forward_flag = False
      self.backward_flag = False
      self.planedPath = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dBh2B().pack(_x.timestamp, _x.Go, _x.Estop, _x.forward_flag, _x.backward_flag))
      length = len(self.planedPath)
      buff.write(_struct_I.pack(length))
      for val1 in self.planedPath:
        _x = val1
        buff.write(_get_struct_6d().pack(_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.planedPath is None:
        self.planedPath = None
      end = 0
      _x = self
      start = end
      end += 13
      (_x.timestamp, _x.Go, _x.Estop, _x.forward_flag, _x.backward_flag,) = _get_struct_dBh2B().unpack(str[start:end])
      self.Go = bool(self.Go)
      self.forward_flag = bool(self.forward_flag)
      self.backward_flag = bool(self.backward_flag)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.planedPath = []
      for i in range(0, length):
        val1 = cav_msgs.msg.Point()
        _x = val1
        start = end
        end += 48
        (_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr,) = _get_struct_6d().unpack(str[start:end])
        self.planedPath.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dBh2B().pack(_x.timestamp, _x.Go, _x.Estop, _x.forward_flag, _x.backward_flag))
      length = len(self.planedPath)
      buff.write(_struct_I.pack(length))
      for val1 in self.planedPath:
        _x = val1
        buff.write(_get_struct_6d().pack(_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.planedPath is None:
        self.planedPath = None
      end = 0
      _x = self
      start = end
      end += 13
      (_x.timestamp, _x.Go, _x.Estop, _x.forward_flag, _x.backward_flag,) = _get_struct_dBh2B().unpack(str[start:end])
      self.Go = bool(self.Go)
      self.forward_flag = bool(self.forward_flag)
      self.backward_flag = bool(self.backward_flag)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.planedPath = []
      for i in range(0, length):
        val1 = cav_msgs.msg.Point()
        _x = val1
        start = end
        end += 48
        (_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr,) = _get_struct_6d().unpack(str[start:end])
        self.planedPath.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_dBh2B = None
def _get_struct_dBh2B():
    global _struct_dBh2B
    if _struct_dBh2B is None:
        _struct_dBh2B = struct.Struct("<dBh2B")
    return _struct_dBh2B
