# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/RefPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RefPoint(genpy.Message):
  _md5sum = "4578623091705a57837c7e08dd996a1f"
  _type = "cav_msgs/RefPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#reference path
float64 t   # time of this point
float64 x
float64 y
float64 v
float64 heading
float64 cr

#drivable area
float64 	left_width
float64 	right_width"""
  __slots__ = ['t','x','y','v','heading','cr','left_width','right_width']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       t,x,y,v,heading,cr,left_width,right_width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RefPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.t is None:
        self.t = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.v is None:
        self.v = 0.
      if self.heading is None:
        self.heading = 0.
      if self.cr is None:
        self.cr = 0.
      if self.left_width is None:
        self.left_width = 0.
      if self.right_width is None:
        self.right_width = 0.
    else:
      self.t = 0.
      self.x = 0.
      self.y = 0.
      self.v = 0.
      self.heading = 0.
      self.cr = 0.
      self.left_width = 0.
      self.right_width = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.t, _x.x, _x.y, _x.v, _x.heading, _x.cr, _x.left_width, _x.right_width,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
