# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cav_msgs/VehicleState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehicleState(genpy.Message):
  _md5sum = "66d93e01fe7d910289d2565124742db5"
  _type = "cav_msgs/VehicleState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """## timestamp, ros time or utc time
float64 timestamp 

## RTK state
string 	RTK_state_string
int64   RTK_seq_num
int64   RTK_timestamp_sec
int64   RTK_timestamp_nsec

int16   RTK_gps_status
int16   RTK_gps_service


## RTK position
float64 RTK_gps_longitude   #degree
float64 RTK_gps_latitude    #degree
float64 RTK_gps_altitude    #m

##position of c.g.
float64 RTK_gps_UTM_x       #meter
float64 RTK_gps_UTM_y       #meter
float64 RTK_gps_UTM_z       #meter


##RTK ENU speed, m/s, global coordinate system
float64 RTK_linear_ENU_vx
float64 RTK_linear_ENU_vy
float64 RTK_linear_ENU_vz

##RTK local coordinate system, m/s
float64 RTK_linear_vx
float64 RTK_linear_vy
float64 RTK_linear_vz

##RTK local angular speed, m/s
float64 RTK_angular_vx
float64 RTK_angular_vy
float64 RTK_angular_vz

##key vehicle state
##position, meter
float64 x
float64 y
float64 z

##RTK local coordinate system, m/s
float64 speed_x
float64 speed_y
float64 speed_z

## acceleration m/s2
float64 acc_x
float64 acc_y
float64 acc_z

## rad
float64 heading         #yaw, rad
float64 pitch           #rad
float64 roll            #rad
float64 yaw_rate        #rad/s

##vehicle size
float64 size_x          #meter
float64 size_y          #meter
float64 size_z          #meter
float64 wheelbase       #meter

##gear position
#GEAR_NONE       (0)
#GEAR_PARK       (1)
#GEAR_REVERSE    (2)
#GEAR_NEUTRAL    (3)
#GEAR_DRIVE      (4)
#GEAR_LOW        (5)
int16   gear_pos


#by-wire, true or false
bool    by_wire_enabled
int16   vehicle_mode         # vehicle mode feedback 0：remote mode, 1：self driving mode


## vehicle state from CAN bus
float64 throttle_cmd
float64 throttle_input
float64 throttle_state      #percentage %
bool    throttle_enabled
bool    throttle_override
bool    throttle_driver
bool    throttle_timeout

float64 brake_cmd
float64 brake_input
float64 brake_state         #percentage %
float64 brake_torq_cmd
float64 brake_torq_input
float64 brake_torq_state
bool    brake_boo_output
bool    brake_enabled
bool    brake_override
bool    brake_driver
bool    brake_timeout

float64 steer_cmd
float64 steer_state_front_wheel # rad
float64 steer_torque
bool    steer_enabled
bool    steer_override
bool    steer_timeout


## Batter and Engine
float64 battery_volt        # V
float64 battery_SOC         # %
int16 engine_speed          # r/min

int16 vehicle_bug_code
int16 vehicle_state_code 

"""
  __slots__ = ['timestamp','RTK_state_string','RTK_seq_num','RTK_timestamp_sec','RTK_timestamp_nsec','RTK_gps_status','RTK_gps_service','RTK_gps_longitude','RTK_gps_latitude','RTK_gps_altitude','RTK_gps_UTM_x','RTK_gps_UTM_y','RTK_gps_UTM_z','RTK_linear_ENU_vx','RTK_linear_ENU_vy','RTK_linear_ENU_vz','RTK_linear_vx','RTK_linear_vy','RTK_linear_vz','RTK_angular_vx','RTK_angular_vy','RTK_angular_vz','x','y','z','speed_x','speed_y','speed_z','acc_x','acc_y','acc_z','heading','pitch','roll','yaw_rate','size_x','size_y','size_z','wheelbase','gear_pos','by_wire_enabled','vehicle_mode','throttle_cmd','throttle_input','throttle_state','throttle_enabled','throttle_override','throttle_driver','throttle_timeout','brake_cmd','brake_input','brake_state','brake_torq_cmd','brake_torq_input','brake_torq_state','brake_boo_output','brake_enabled','brake_override','brake_driver','brake_timeout','steer_cmd','steer_state_front_wheel','steer_torque','steer_enabled','steer_override','steer_timeout','battery_volt','battery_SOC','engine_speed','vehicle_bug_code','vehicle_state_code']
  _slot_types = ['float64','string','int64','int64','int64','int16','int16','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int16','bool','int16','float64','float64','float64','bool','bool','bool','bool','float64','float64','float64','float64','float64','float64','bool','bool','bool','bool','bool','float64','float64','float64','bool','bool','bool','float64','float64','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,RTK_state_string,RTK_seq_num,RTK_timestamp_sec,RTK_timestamp_nsec,RTK_gps_status,RTK_gps_service,RTK_gps_longitude,RTK_gps_latitude,RTK_gps_altitude,RTK_gps_UTM_x,RTK_gps_UTM_y,RTK_gps_UTM_z,RTK_linear_ENU_vx,RTK_linear_ENU_vy,RTK_linear_ENU_vz,RTK_linear_vx,RTK_linear_vy,RTK_linear_vz,RTK_angular_vx,RTK_angular_vy,RTK_angular_vz,x,y,z,speed_x,speed_y,speed_z,acc_x,acc_y,acc_z,heading,pitch,roll,yaw_rate,size_x,size_y,size_z,wheelbase,gear_pos,by_wire_enabled,vehicle_mode,throttle_cmd,throttle_input,throttle_state,throttle_enabled,throttle_override,throttle_driver,throttle_timeout,brake_cmd,brake_input,brake_state,brake_torq_cmd,brake_torq_input,brake_torq_state,brake_boo_output,brake_enabled,brake_override,brake_driver,brake_timeout,steer_cmd,steer_state_front_wheel,steer_torque,steer_enabled,steer_override,steer_timeout,battery_volt,battery_SOC,engine_speed,vehicle_bug_code,vehicle_state_code

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.RTK_state_string is None:
        self.RTK_state_string = ''
      if self.RTK_seq_num is None:
        self.RTK_seq_num = 0
      if self.RTK_timestamp_sec is None:
        self.RTK_timestamp_sec = 0
      if self.RTK_timestamp_nsec is None:
        self.RTK_timestamp_nsec = 0
      if self.RTK_gps_status is None:
        self.RTK_gps_status = 0
      if self.RTK_gps_service is None:
        self.RTK_gps_service = 0
      if self.RTK_gps_longitude is None:
        self.RTK_gps_longitude = 0.
      if self.RTK_gps_latitude is None:
        self.RTK_gps_latitude = 0.
      if self.RTK_gps_altitude is None:
        self.RTK_gps_altitude = 0.
      if self.RTK_gps_UTM_x is None:
        self.RTK_gps_UTM_x = 0.
      if self.RTK_gps_UTM_y is None:
        self.RTK_gps_UTM_y = 0.
      if self.RTK_gps_UTM_z is None:
        self.RTK_gps_UTM_z = 0.
      if self.RTK_linear_ENU_vx is None:
        self.RTK_linear_ENU_vx = 0.
      if self.RTK_linear_ENU_vy is None:
        self.RTK_linear_ENU_vy = 0.
      if self.RTK_linear_ENU_vz is None:
        self.RTK_linear_ENU_vz = 0.
      if self.RTK_linear_vx is None:
        self.RTK_linear_vx = 0.
      if self.RTK_linear_vy is None:
        self.RTK_linear_vy = 0.
      if self.RTK_linear_vz is None:
        self.RTK_linear_vz = 0.
      if self.RTK_angular_vx is None:
        self.RTK_angular_vx = 0.
      if self.RTK_angular_vy is None:
        self.RTK_angular_vy = 0.
      if self.RTK_angular_vz is None:
        self.RTK_angular_vz = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.speed_x is None:
        self.speed_x = 0.
      if self.speed_y is None:
        self.speed_y = 0.
      if self.speed_z is None:
        self.speed_z = 0.
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.heading is None:
        self.heading = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.roll is None:
        self.roll = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.size_x is None:
        self.size_x = 0.
      if self.size_y is None:
        self.size_y = 0.
      if self.size_z is None:
        self.size_z = 0.
      if self.wheelbase is None:
        self.wheelbase = 0.
      if self.gear_pos is None:
        self.gear_pos = 0
      if self.by_wire_enabled is None:
        self.by_wire_enabled = False
      if self.vehicle_mode is None:
        self.vehicle_mode = 0
      if self.throttle_cmd is None:
        self.throttle_cmd = 0.
      if self.throttle_input is None:
        self.throttle_input = 0.
      if self.throttle_state is None:
        self.throttle_state = 0.
      if self.throttle_enabled is None:
        self.throttle_enabled = False
      if self.throttle_override is None:
        self.throttle_override = False
      if self.throttle_driver is None:
        self.throttle_driver = False
      if self.throttle_timeout is None:
        self.throttle_timeout = False
      if self.brake_cmd is None:
        self.brake_cmd = 0.
      if self.brake_input is None:
        self.brake_input = 0.
      if self.brake_state is None:
        self.brake_state = 0.
      if self.brake_torq_cmd is None:
        self.brake_torq_cmd = 0.
      if self.brake_torq_input is None:
        self.brake_torq_input = 0.
      if self.brake_torq_state is None:
        self.brake_torq_state = 0.
      if self.brake_boo_output is None:
        self.brake_boo_output = False
      if self.brake_enabled is None:
        self.brake_enabled = False
      if self.brake_override is None:
        self.brake_override = False
      if self.brake_driver is None:
        self.brake_driver = False
      if self.brake_timeout is None:
        self.brake_timeout = False
      if self.steer_cmd is None:
        self.steer_cmd = 0.
      if self.steer_state_front_wheel is None:
        self.steer_state_front_wheel = 0.
      if self.steer_torque is None:
        self.steer_torque = 0.
      if self.steer_enabled is None:
        self.steer_enabled = False
      if self.steer_override is None:
        self.steer_override = False
      if self.steer_timeout is None:
        self.steer_timeout = False
      if self.battery_volt is None:
        self.battery_volt = 0.
      if self.battery_SOC is None:
        self.battery_SOC = 0.
      if self.engine_speed is None:
        self.engine_speed = 0
      if self.vehicle_bug_code is None:
        self.vehicle_bug_code = 0
      if self.vehicle_state_code is None:
        self.vehicle_state_code = 0
    else:
      self.timestamp = 0.
      self.RTK_state_string = ''
      self.RTK_seq_num = 0
      self.RTK_timestamp_sec = 0
      self.RTK_timestamp_nsec = 0
      self.RTK_gps_status = 0
      self.RTK_gps_service = 0
      self.RTK_gps_longitude = 0.
      self.RTK_gps_latitude = 0.
      self.RTK_gps_altitude = 0.
      self.RTK_gps_UTM_x = 0.
      self.RTK_gps_UTM_y = 0.
      self.RTK_gps_UTM_z = 0.
      self.RTK_linear_ENU_vx = 0.
      self.RTK_linear_ENU_vy = 0.
      self.RTK_linear_ENU_vz = 0.
      self.RTK_linear_vx = 0.
      self.RTK_linear_vy = 0.
      self.RTK_linear_vz = 0.
      self.RTK_angular_vx = 0.
      self.RTK_angular_vy = 0.
      self.RTK_angular_vz = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.speed_x = 0.
      self.speed_y = 0.
      self.speed_z = 0.
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.heading = 0.
      self.pitch = 0.
      self.roll = 0.
      self.yaw_rate = 0.
      self.size_x = 0.
      self.size_y = 0.
      self.size_z = 0.
      self.wheelbase = 0.
      self.gear_pos = 0
      self.by_wire_enabled = False
      self.vehicle_mode = 0
      self.throttle_cmd = 0.
      self.throttle_input = 0.
      self.throttle_state = 0.
      self.throttle_enabled = False
      self.throttle_override = False
      self.throttle_driver = False
      self.throttle_timeout = False
      self.brake_cmd = 0.
      self.brake_input = 0.
      self.brake_state = 0.
      self.brake_torq_cmd = 0.
      self.brake_torq_input = 0.
      self.brake_torq_state = 0.
      self.brake_boo_output = False
      self.brake_enabled = False
      self.brake_override = False
      self.brake_driver = False
      self.brake_timeout = False
      self.steer_cmd = 0.
      self.steer_state_front_wheel = 0.
      self.steer_torque = 0.
      self.steer_enabled = False
      self.steer_override = False
      self.steer_timeout = False
      self.battery_volt = 0.
      self.battery_SOC = 0.
      self.engine_speed = 0
      self.vehicle_bug_code = 0
      self.vehicle_state_code = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.timestamp
      buff.write(_get_struct_d().pack(_x))
      _x = self.RTK_state_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3q2h32dhBh3d4B6d5B3d3B2d3h().pack(_x.RTK_seq_num, _x.RTK_timestamp_sec, _x.RTK_timestamp_nsec, _x.RTK_gps_status, _x.RTK_gps_service, _x.RTK_gps_longitude, _x.RTK_gps_latitude, _x.RTK_gps_altitude, _x.RTK_gps_UTM_x, _x.RTK_gps_UTM_y, _x.RTK_gps_UTM_z, _x.RTK_linear_ENU_vx, _x.RTK_linear_ENU_vy, _x.RTK_linear_ENU_vz, _x.RTK_linear_vx, _x.RTK_linear_vy, _x.RTK_linear_vz, _x.RTK_angular_vx, _x.RTK_angular_vy, _x.RTK_angular_vz, _x.x, _x.y, _x.z, _x.speed_x, _x.speed_y, _x.speed_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.heading, _x.pitch, _x.roll, _x.yaw_rate, _x.size_x, _x.size_y, _x.size_z, _x.wheelbase, _x.gear_pos, _x.by_wire_enabled, _x.vehicle_mode, _x.throttle_cmd, _x.throttle_input, _x.throttle_state, _x.throttle_enabled, _x.throttle_override, _x.throttle_driver, _x.throttle_timeout, _x.brake_cmd, _x.brake_input, _x.brake_state, _x.brake_torq_cmd, _x.brake_torq_input, _x.brake_torq_state, _x.brake_boo_output, _x.brake_enabled, _x.brake_override, _x.brake_driver, _x.brake_timeout, _x.steer_cmd, _x.steer_state_front_wheel, _x.steer_torque, _x.steer_enabled, _x.steer_override, _x.steer_timeout, _x.battery_volt, _x.battery_SOC, _x.engine_speed, _x.vehicle_bug_code, _x.vehicle_state_code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.RTK_state_string = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.RTK_state_string = str[start:end]
      _x = self
      start = end
      end += 419
      (_x.RTK_seq_num, _x.RTK_timestamp_sec, _x.RTK_timestamp_nsec, _x.RTK_gps_status, _x.RTK_gps_service, _x.RTK_gps_longitude, _x.RTK_gps_latitude, _x.RTK_gps_altitude, _x.RTK_gps_UTM_x, _x.RTK_gps_UTM_y, _x.RTK_gps_UTM_z, _x.RTK_linear_ENU_vx, _x.RTK_linear_ENU_vy, _x.RTK_linear_ENU_vz, _x.RTK_linear_vx, _x.RTK_linear_vy, _x.RTK_linear_vz, _x.RTK_angular_vx, _x.RTK_angular_vy, _x.RTK_angular_vz, _x.x, _x.y, _x.z, _x.speed_x, _x.speed_y, _x.speed_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.heading, _x.pitch, _x.roll, _x.yaw_rate, _x.size_x, _x.size_y, _x.size_z, _x.wheelbase, _x.gear_pos, _x.by_wire_enabled, _x.vehicle_mode, _x.throttle_cmd, _x.throttle_input, _x.throttle_state, _x.throttle_enabled, _x.throttle_override, _x.throttle_driver, _x.throttle_timeout, _x.brake_cmd, _x.brake_input, _x.brake_state, _x.brake_torq_cmd, _x.brake_torq_input, _x.brake_torq_state, _x.brake_boo_output, _x.brake_enabled, _x.brake_override, _x.brake_driver, _x.brake_timeout, _x.steer_cmd, _x.steer_state_front_wheel, _x.steer_torque, _x.steer_enabled, _x.steer_override, _x.steer_timeout, _x.battery_volt, _x.battery_SOC, _x.engine_speed, _x.vehicle_bug_code, _x.vehicle_state_code,) = _get_struct_3q2h32dhBh3d4B6d5B3d3B2d3h().unpack(str[start:end])
      self.by_wire_enabled = bool(self.by_wire_enabled)
      self.throttle_enabled = bool(self.throttle_enabled)
      self.throttle_override = bool(self.throttle_override)
      self.throttle_driver = bool(self.throttle_driver)
      self.throttle_timeout = bool(self.throttle_timeout)
      self.brake_boo_output = bool(self.brake_boo_output)
      self.brake_enabled = bool(self.brake_enabled)
      self.brake_override = bool(self.brake_override)
      self.brake_driver = bool(self.brake_driver)
      self.brake_timeout = bool(self.brake_timeout)
      self.steer_enabled = bool(self.steer_enabled)
      self.steer_override = bool(self.steer_override)
      self.steer_timeout = bool(self.steer_timeout)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.timestamp
      buff.write(_get_struct_d().pack(_x))
      _x = self.RTK_state_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3q2h32dhBh3d4B6d5B3d3B2d3h().pack(_x.RTK_seq_num, _x.RTK_timestamp_sec, _x.RTK_timestamp_nsec, _x.RTK_gps_status, _x.RTK_gps_service, _x.RTK_gps_longitude, _x.RTK_gps_latitude, _x.RTK_gps_altitude, _x.RTK_gps_UTM_x, _x.RTK_gps_UTM_y, _x.RTK_gps_UTM_z, _x.RTK_linear_ENU_vx, _x.RTK_linear_ENU_vy, _x.RTK_linear_ENU_vz, _x.RTK_linear_vx, _x.RTK_linear_vy, _x.RTK_linear_vz, _x.RTK_angular_vx, _x.RTK_angular_vy, _x.RTK_angular_vz, _x.x, _x.y, _x.z, _x.speed_x, _x.speed_y, _x.speed_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.heading, _x.pitch, _x.roll, _x.yaw_rate, _x.size_x, _x.size_y, _x.size_z, _x.wheelbase, _x.gear_pos, _x.by_wire_enabled, _x.vehicle_mode, _x.throttle_cmd, _x.throttle_input, _x.throttle_state, _x.throttle_enabled, _x.throttle_override, _x.throttle_driver, _x.throttle_timeout, _x.brake_cmd, _x.brake_input, _x.brake_state, _x.brake_torq_cmd, _x.brake_torq_input, _x.brake_torq_state, _x.brake_boo_output, _x.brake_enabled, _x.brake_override, _x.brake_driver, _x.brake_timeout, _x.steer_cmd, _x.steer_state_front_wheel, _x.steer_torque, _x.steer_enabled, _x.steer_override, _x.steer_timeout, _x.battery_volt, _x.battery_SOC, _x.engine_speed, _x.vehicle_bug_code, _x.vehicle_state_code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.RTK_state_string = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.RTK_state_string = str[start:end]
      _x = self
      start = end
      end += 419
      (_x.RTK_seq_num, _x.RTK_timestamp_sec, _x.RTK_timestamp_nsec, _x.RTK_gps_status, _x.RTK_gps_service, _x.RTK_gps_longitude, _x.RTK_gps_latitude, _x.RTK_gps_altitude, _x.RTK_gps_UTM_x, _x.RTK_gps_UTM_y, _x.RTK_gps_UTM_z, _x.RTK_linear_ENU_vx, _x.RTK_linear_ENU_vy, _x.RTK_linear_ENU_vz, _x.RTK_linear_vx, _x.RTK_linear_vy, _x.RTK_linear_vz, _x.RTK_angular_vx, _x.RTK_angular_vy, _x.RTK_angular_vz, _x.x, _x.y, _x.z, _x.speed_x, _x.speed_y, _x.speed_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.heading, _x.pitch, _x.roll, _x.yaw_rate, _x.size_x, _x.size_y, _x.size_z, _x.wheelbase, _x.gear_pos, _x.by_wire_enabled, _x.vehicle_mode, _x.throttle_cmd, _x.throttle_input, _x.throttle_state, _x.throttle_enabled, _x.throttle_override, _x.throttle_driver, _x.throttle_timeout, _x.brake_cmd, _x.brake_input, _x.brake_state, _x.brake_torq_cmd, _x.brake_torq_input, _x.brake_torq_state, _x.brake_boo_output, _x.brake_enabled, _x.brake_override, _x.brake_driver, _x.brake_timeout, _x.steer_cmd, _x.steer_state_front_wheel, _x.steer_torque, _x.steer_enabled, _x.steer_override, _x.steer_timeout, _x.battery_volt, _x.battery_SOC, _x.engine_speed, _x.vehicle_bug_code, _x.vehicle_state_code,) = _get_struct_3q2h32dhBh3d4B6d5B3d3B2d3h().unpack(str[start:end])
      self.by_wire_enabled = bool(self.by_wire_enabled)
      self.throttle_enabled = bool(self.throttle_enabled)
      self.throttle_override = bool(self.throttle_override)
      self.throttle_driver = bool(self.throttle_driver)
      self.throttle_timeout = bool(self.throttle_timeout)
      self.brake_boo_output = bool(self.brake_boo_output)
      self.brake_enabled = bool(self.brake_enabled)
      self.brake_override = bool(self.brake_override)
      self.brake_driver = bool(self.brake_driver)
      self.brake_timeout = bool(self.brake_timeout)
      self.steer_enabled = bool(self.steer_enabled)
      self.steer_override = bool(self.steer_override)
      self.steer_timeout = bool(self.steer_timeout)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3q2h32dhBh3d4B6d5B3d3B2d3h = None
def _get_struct_3q2h32dhBh3d4B6d5B3d3B2d3h():
    global _struct_3q2h32dhBh3d4B6d5B3d3B2d3h
    if _struct_3q2h32dhBh3d4B6d5B3d3B2d3h is None:
        _struct_3q2h32dhBh3d4B6d5B3d3B2d3h = struct.Struct("<3q2h32dhBh3d4B6d5B3d3B2d3h")
    return _struct_3q2h32dhBh3d4B6d5B3d3B2d3h
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
