(cl:in-package cav_msgs-msg)
(cl:export '(SERIAL_NUMBER-VAL
          SERIAL_NUMBER
          UTC-VAL
          UTC
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          NORTH_VEL-VAL
          NORTH_VEL
          EAST_VEL-VAL
          EAST_VEL
          EARTH_VEL-VAL
          EARTH_VEL
          VEL-VAL
          VEL
          GAUSSIAN_X-VAL
          GAUSSIAN_X
          GAUSSIAN_Y-VAL
          GAUSSIAN_Y
          BASE_STATION_X-VAL
          BASE_STATION_X
          BASE_STATION_Y-VAL
          BASE_STATION_Y
          STATUS-VAL
          STATUS
          STATUS_VICE-VAL
          STATUS_VICE
))