(cl:in-package cav_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          RTK_STATE_STRING-VAL
          RTK_STATE_STRING
          RTK_SEQ_NUM-VAL
          RTK_SEQ_NUM
          RTK_TIMESTAMP_SEC-VAL
          RTK_TIMESTAMP_SEC
          RTK_TIMESTAMP_NSEC-VAL
          RTK_TIMESTAMP_NSEC
          RTK_GPS_STATUS-VAL
          RTK_GPS_STATUS
          RTK_GPS_SERVICE-VAL
          RTK_GPS_SERVICE
          RTK_GPS_LONGITUDE-VAL
          RTK_GPS_LONGITUDE
          RTK_GPS_LATITUDE-VAL
          RTK_GPS_LATITUDE
          RTK_GPS_ALTITUDE-VAL
          RTK_GPS_ALTITUDE
          RTK_GPS_UTM_X-VAL
          RTK_GPS_UTM_X
          RTK_GPS_UTM_Y-VAL
          RTK_GPS_UTM_Y
          RTK_GPS_UTM_Z-VAL
          RTK_GPS_UTM_Z
          RTK_LINEAR_ENU_VX-VAL
          RTK_LINEAR_ENU_VX
          RTK_LINEAR_ENU_VY-VAL
          RTK_LINEAR_ENU_VY
          RTK_LINEAR_ENU_VZ-VAL
          RTK_LINEAR_ENU_VZ
          RTK_LINEAR_VX-VAL
          RTK_LINEAR_VX
          RTK_LINEAR_VY-VAL
          RTK_LINEAR_VY
          RTK_LINEAR_VZ-VAL
          RTK_LINEAR_VZ
          RTK_ANGULAR_VX-VAL
          RTK_ANGULAR_VX
          RTK_ANGULAR_VY-VAL
          RTK_ANGULAR_VY
          RTK_ANGULAR_VZ-VAL
          RTK_ANGULAR_VZ
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          SPEED_X-VAL
          SPEED_X
          SPEED_Y-VAL
          SPEED_Y
          SPEED_Z-VAL
          SPEED_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW_RATE-VAL
          YAW_RATE
          SIZE_X-VAL
          SIZE_X
          SIZE_Y-VAL
          SIZE_Y
          SIZE_Z-VAL
          SIZE_Z
          WHEELBASE-VAL
          WHEELBASE
          GEAR_POS-VAL
          GEAR_POS
          BY_WIRE_ENABLED-VAL
          BY_WIRE_ENABLED
          VEHICLE_MODE-VAL
          VEHICLE_MODE
          THROTTLE_CMD-VAL
          THROTTLE_CMD
          THROTTLE_INPUT-VAL
          THROTTLE_INPUT
          THROTTLE_STATE-VAL
          THROTTLE_STATE
          THROTTLE_ENABLED-VAL
          THROTTLE_ENABLED
          THROTTLE_OVERRIDE-VAL
          THROTTLE_OVERRIDE
          THROTTLE_DRIVER-VAL
          THROTTLE_DRIVER
          THROTTLE_TIMEOUT-VAL
          THROTTLE_TIMEOUT
          BRAKE_CMD-VAL
          BRAKE_CMD
          BRAKE_INPUT-VAL
          BRAKE_INPUT
          BRAKE_STATE-VAL
          BRAKE_STATE
          BRAKE_TORQ_CMD-VAL
          BRAKE_TORQ_CMD
          BRAKE_TORQ_INPUT-VAL
          BRAKE_TORQ_INPUT
          BRAKE_TORQ_STATE-VAL
          BRAKE_TORQ_STATE
          BRAKE_BOO_OUTPUT-VAL
          BRAKE_BOO_OUTPUT
          BRAKE_ENABLED-VAL
          BRAKE_ENABLED
          BRAKE_OVERRIDE-VAL
          BRAKE_OVERRIDE
          BRAKE_DRIVER-VAL
          BRAKE_DRIVER
          BRAKE_TIMEOUT-VAL
          BRAKE_TIMEOUT
          STEER_CMD-VAL
          STEER_CMD
          STEER_STATE_FRONT_WHEEL-VAL
          STEER_STATE_FRONT_WHEEL
          STEER_TORQUE-VAL
          STEER_TORQUE
          STEER_ENABLED-VAL
          STEER_ENABLED
          STEER_OVERRIDE-VAL
          STEER_OVERRIDE
          STEER_TIMEOUT-VAL
          STEER_TIMEOUT
          BATTERY_VOLT-VAL
          BATTERY_VOLT
          BATTERY_SOC-VAL
          BATTERY_SOC
          ENGINE_SPEED-VAL
          ENGINE_SPEED
          VEHICLE_BUG_CODE-VAL
          VEHICLE_BUG_CODE
          VEHICLE_STATE_CODE-VAL
          VEHICLE_STATE_CODE
))