(cl:in-package cav_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          COUNT-VAL
          COUNT
          BRAKE_CMD-VAL
          BRAKE_CMD
          THROTTLE_CMD-VAL
          THROTTLE_CMD
          STEERING_CMD_FRONT_WHEEL-VAL
          STEERING_CMD_FRONT_WHEEL
          GEAR_CMD-VAL
          GEAR_CMD
          TURN_SIGNAL_CMD-VAL
          TURN_SIGNAL_CMD
          SPEED_CMD-VAL
          SPEED_CMD
          ACCELERATION_CMD-VAL
          ACCELERATION_CMD
          BYWIRE_CONTROL_ENABLE-VAL
          BYWIRE_CONTROL_ENABLE
          EMERG_BRAKE-VAL
          EMERG_BRAKE
          FRONT_LIGHT-VAL
          FRONT_LIGHT
          ENGINE_ENABLE-VAL
          ENGINE_ENABLE
          PARK_ENABLE-VAL
          PARK_ENABLE
          VEHICLE_MODE-VAL
          VEHICLE_MODE
          YAW_SPEED_CMD-VAL
          YAW_SPEED_CMD
          EY_OUT-VAL
          EY_OUT
          EPHI_OUT-VAL
          EPHI_OUT
))